
<h1>新闻查询</h1>
<form action="/admin/jouralism/query" method="post">
<input type="text" name="query">
    <input type="submit" value="提交">
</form>

<h1>新闻列表</h1>

<form action="/admin/jouralism/deletejouralism" method="post">
    <table class="datalist fixwidth">
        <tbody>
        <tr>
            <th nowrap="nowrap"><input name="chkall" id="id" class="checkbox" type="checkbox"><label for="chkall">删除</label></th>
            <th nowrap="nowrap">新闻名称</th>
            <th nowrap="nowrap">新闻内容</th>
            <th nowrap="nowrap">时间</th>
            <th nowrap="nowrap">详情</th>
        </tr>
        <?php foreach ($data as $row) {;?>
        <tr>
            <td width="80"><input name="id" value="<?=$row['jouralismId'];?>" class="checkbox" type="checkbox"></td>
            <td width="300"><?=mb_substr($row['jouralismTitle'], 0, 20);?></td>
            <th nowrap="400"><?=mb_substr($row['jouralismContent'], 0, 50);?></th>
            <th nowrap="100"><?=date('Y-m-d', $row['jouralismTime']);?></th>
            <td width="100"><a href="/admin/jouralism/jouralism?id=<?=$row['jouralismId'];?>">编辑</a></td>
        </tr>
        <?php }
;?>

        <tr class="nobg">
            <td ><input value="提 交" class="btn" type="submit"></td>
        </tr>
        <?=$page;?>
        </tbody>
    </table>
</form>